/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * BatchAnalysisDialog.java
 *
 * Created on Mar 12, 2014, 3:10:32 PM
 */
package gui;

import java.awt.Point;
import java.awt.event.WindowEvent;
import java.io.File;
import java.io.IOException;
import java.util.logging.Logger;

import javax.swing.JFileChooser;
import javax.swing.filechooser.FileNameExtensionFilter;

import db.PathwayImpl;

/**
 *
 * @author ufuk
 */
public class BatchAnalysisDialog extends javax.swing.JDialog {

	private static final long serialVersionUID = -6656504571602104722L;

	public static Logger logger = Logger.getLogger(PathwayImpl.class.getName());

	/** Creates new form BatchAnalysisDialog */
    public BatchAnalysisDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }
    
    public File[] getFiles(){
    	return files;
    }
    

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        batchFilesTextArea = new javax.swing.JTextArea();
        descriptionLabel = new javax.swing.JLabel();
        nextButton = new javax.swing.JButton();
        addFileButton = new javax.swing.JButton();
        editParamButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        batchFilesTextArea.setColumns(20);
        batchFilesTextArea.setRows(5);
        jScrollPane1.setViewportView(batchFilesTextArea);

        descriptionLabel.setText("<html>Please choose the datafiles for this batch analysis by adding files to the below text area. You can drag'n drop them or add them by browsing the file system.  \n<p>\n<p>Note that the resultant analyses will be named based on the filenames and that the same analysis parameters will be used for all files, please make sure that all your files have the same structure and same type of quantification values.");

        nextButton.setText("Next ->");
        nextButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextButtonActionPerformed(evt);
            }
        });

        addFileButton.setText("Add files...");
        addFileButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addFileButtonActionPerformed(evt);
            }
        });

        editParamButton.setText("Parameters");
        editParamButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editParamButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(descriptionLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 464, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 309, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nextButton, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
                            .addComponent(editParamButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
                            .addComponent(addFileButton, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(descriptionLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(addFileButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(editParamButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(nextButton))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 317, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(113, 113, 113))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

	private void nextButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextButtonActionPerformed
		dispatchEvent(new WindowEvent(this, WindowEvent.WINDOW_CLOSING));
		setVisible(false);
	}//GEN-LAST:event_nextButtonActionPerformed
	
	private void addFileButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addFileButtonActionPerformed
		/* TODO
		 * Show file chooser
		 */
		JFileChooser jfc = new JFileChooser();
		Point loc = getLocation();
		loc.translate(20, 20);
		jfc.setLocation(loc);
		jfc.setVisible(true);
		jfc.setFileSelectionMode(JFileChooser.FILES_ONLY);
		jfc.setMultiSelectionEnabled(true);
		jfc.setFileFilter(
			new FileNameExtensionFilter(
					"Comma or tab separated text files", 
					"txt", "csv", "tsv"));

		if (jfc.showOpenDialog(null) == JFileChooser.APPROVE_OPTION) {
			try {
				files = jfc.getSelectedFiles();
				for(File f : files)
					batchFilesTextArea.append(
						f.getCanonicalPath() + 
						System.getProperty("line.separator"));
			} catch (IOException e) {
				e.printStackTrace();
			}
		}
	}//GEN-LAST:event_addFileButtonActionPerformed
	
	private void editParamButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editParamButtonActionPerformed
		/* TODO
		 * Show analysis parameters
		 */
	}//GEN-LAST:event_editParamButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addFileButton;
    private javax.swing.JTextArea batchFilesTextArea;
    private javax.swing.JLabel descriptionLabel;
    private javax.swing.JButton editParamButton;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton nextButton;
    // End of variables declaration//GEN-END:variables
    private File[] files;
}
