/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * TestPanel.java
 *
 * Created on Jun 4, 2014, 9:22:14 AM
 */
package gui;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.logging.Logger;

import javax.swing.ImageIcon;
import javax.swing.JDesktopPane;
import javax.swing.JTextPane;
import javax.swing.JFrame;
import javax.swing.UIDefaults;
import javax.swing.event.InternalFrameListener;

import db.PathwayImpl;

/**
 *
 * @author ufuk
 */
public class FeverMainPanel extends javax.swing.JPanel {

	/**
	 * 
	 */
	private static final long serialVersionUID = 845150329617452725L;
	public static Logger logger = Logger.getLogger(PathwayImpl.class.getName());

	
    /** Creates new form TestPanel */
    public FeverMainPanel() {
        initComponents();
        
        dpane.setDragMode(JDesktopPane.OUTLINE_DRAG_MODE);
        
        // Fix for Nimbus L&F override 
        // makes sure the colors of the textPane are correct
        UIDefaults defaults = new UIDefaults();
	    defaults.put("TextPane[Enabled].backgroundPainter", Color.LIGHT_GRAY);
	    defaults.put("TextPane[Enabled].foregroundPainter", Color.DARK_GRAY);
	    tpane.putClientProperty("Nimbus.Overrides", defaults);
	    tpane.putClientProperty("Nimbus.Overrides.InheritDefaults", true);
	    tpane.setBackground(Color.LIGHT_GRAY);
	    tpane.setForeground(Color.DARK_GRAY);
	    
	    // Button cosmetics and actionHandler 
//		rightArrowIcon = new ImageIcon(getClass().getResource("../aright.png"));
//		leftArrowIcon = new ImageIcon(getClass().getResource("../aleft.png"));
//		hideButton.setIcon(leftArrowIcon);
		hideButton.addActionListener(new ActionListener() {
			@Override
			public void actionPerformed(ActionEvent e) {
				Dimension d = dpane.getSize();
				Dimension s = spane.getSize();

				if (spane.isVisible()) {
					spane.setVisible(false);
					dpane.setSize(new Dimension(d.width + s.width, d.height));
//					hideButton.setIcon(rightArrowIcon);
				} else {
					spane.setVisible(true);
					dpane.setSize(new Dimension(d.width - s.width, d.height));
//					hideButton.setIcon(leftArrowIcon);
				}
				((JFrame) getTopLevelAncestor()).validate();
			}
		});
    }
    
    
    public JDesktopPane getDesktop(){
    	return this.dpane;
    }
    
    public JTextPane getTextPane(){
    	return this.tpane;
    }
    
    public void setHideButtonActionListener(ActionListener a){
    	this.hideButton.addActionListener(a);
    }
    
    public InternalAnalysisFrame newAnalysisFrame(String title, InternalFrameListener ifl){
    	InternalAnalysisFrame frame = new InternalAnalysisFrame(title);
		frame.addInternalFrameListener(ifl);		
    	frame.setVisible(true);
    	dpane.add(frame);
    	logger.info("Initiating new analysis: " + title + System.lineSeparator());
    	
        try {
            frame.setSelected(true);
        } catch (java.beans.PropertyVetoException e) {
        	e.printStackTrace();
        }
        dpane.repaint();
        return frame;
	}
    

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dpane = new javax.swing.JDesktopPane();
        spane = new javax.swing.JScrollPane();
        tpane = new javax.swing.JTextPane();
        hideButton = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(1280, 778));

        dpane.setPreferredSize(new java.awt.Dimension(820, 778));
        dpane.setLayout(null);

        tpane.setEditable(false);
        tpane.setBackground(java.awt.Color.lightGray);
        tpane.setBorder(javax.swing.BorderFactory.createTitledBorder(null, " Console ", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Lucida Grande", 0, 13), java.awt.Color.darkGray)); // NOI18N
        tpane.setForeground(java.awt.Color.darkGray);
        spane.setViewportView(tpane);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(dpane, javax.swing.GroupLayout.DEFAULT_SIZE, 670, Short.MAX_VALUE)
                .addGap(0, 0, 0)
                .addComponent(hideButton, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(spane, javax.swing.GroupLayout.PREFERRED_SIZE, 596, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(hideButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(dpane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(spane)
        );
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane dpane;
    private javax.swing.JButton hideButton;
    private javax.swing.JScrollPane spane;
    private javax.swing.JTextPane tpane;
    // End of variables declaration//GEN-END:variables
    
	private ImageIcon leftArrowIcon, rightArrowIcon;

}
