/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ParamPanel.java
 *
 * Created on Mar 4, 2014, 11:12:36 AM
 */
package gui;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.Enumeration;
import java.util.logging.Logger;

import javax.swing.AbstractButton;
import javax.swing.ButtonGroup;

import db.PathwayImpl;
import main.AnalysisParams;
import main.AnalysisParams.RANDMETHOD;
import main.AnalysisParams.SORTMETHOD;

/**
 *
 * @author ufuk
 */
public class ParamPanel extends javax.swing.JPanel {

	private static final long serialVersionUID = 2301742846551333150L;
	
	public static Logger logger = Logger.getLogger(PathwayImpl.class.getName());


	/** Creates new form ParamPanel */
    public ParamPanel() {
        initComponents();
        okButton.addActionListener(new ActionListener(){
			@Override
			public void actionPerformed(ActionEvent e) {
				ParamPanel.this.setVisible(false);
			}
        });
    }
    
    
    // TODO: is this necessary?! Is the OK button necessary?
    public void setOKButtonAction(ActionListener al){
    	okButton.addActionListener(al);
    }
    
    public RANDMETHOD getRandMethod(){
        AbstractButton butt = getSelectedButton(randButtons);
        String buttext = butt.getText();
        if(buttext.contains(EMPIRICAL_DIST_IDENTIFIER))
        	return RANDMETHOD.EMPIRICAL;
        else if(buttext.contains(PERMUTATION_IDENTIFIER))
        	return RANDMETHOD.PERMUTATION;
        else if(buttext.contains(LOGNORM_IDENTIFIER))
        	return RANDMETHOD.LOGNORM;
    	else
    		return null;
    }
    
    public SORTMETHOD getSortMethod(){
        AbstractButton butt = getSelectedButton(sortButtons);
        String buttext = butt.getText();
        if(buttext.contains(FOLD_CH_IDENTIFIER))
        	return SORTMETHOD.FOLDCHANGE;
        else if(buttext.contains(PVAL_IDENTIFIER))
        	return SORTMETHOD.PVALUE;
    	else if(buttext.contains(COMBINED_IDENTIFIER))
    		return SORTMETHOD.COMB_NONLINEAR;
    	else
    		return null;
    }
    
    public void registerParams(){
    	final AnalysisParams param = AnalysisParams.getInstance();
    	param.addParam(AnalysisParams.a1_key, alpha1Field.getText());
    	param.addParam(AnalysisParams.a2_key, alpha2Field.getText());
    	param.addParam(AnalysisParams.a3_key, alpha3Field.getText());
    	param.addParam(AnalysisParams.k1_key, kappa1Field.getText());
    	param.addParam(AnalysisParams.k2_key, kappa2Field.getText());
    	param.addParam(AnalysisParams.reglevel_key, regField.getText());
    	param.addParam(AnalysisParams.signlevel_key, sigField.getText());
    	param.addParam(AnalysisParams.rand_key, getRandMethod());
    	param.addParam(AnalysisParams.sort_key, getSortMethod());
    	param.addParam(AnalysisParams.nthreads_key, nThreadsField.getText());
    }
    
    private AbstractButton getSelectedButton(ButtonGroup buttonGroup) {
        for (Enumeration<AbstractButton> buttons = buttonGroup.getElements(); buttons.hasMoreElements();) {
            AbstractButton button = buttons.nextElement();
            if (button.isSelected()) 
                return button;
            
        }

        return null;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        sortButtons = new javax.swing.ButtonGroup();
        randButtons = new javax.swing.ButtonGroup();
        roiPanel = new javax.swing.JPanel();
        regLabel = new javax.swing.JLabel();
        regField = new javax.swing.JTextField();
        sigLabel = new javax.swing.JLabel();
        sigField = new javax.swing.JTextField();
        modelParamsPanel = new javax.swing.JPanel();
        alpha1Label = new javax.swing.JLabel();
        alpha1Field = new javax.swing.JTextField();
        alpha2Field = new javax.swing.JTextField();
        alpha2Label = new javax.swing.JLabel();
        alpha3Field = new javax.swing.JTextField();
        alpha3Label = new javax.swing.JLabel();
        kappa2Label = new javax.swing.JLabel();
        kappa2Field = new javax.swing.JTextField();
        kappa1Field = new javax.swing.JTextField();
        kappa1Label = new javax.swing.JLabel();
        statsPanel = new javax.swing.JPanel();
        sortLabel = new javax.swing.JLabel();
        randLabel = new javax.swing.JLabel();
        sortMethodButton1 = new javax.swing.JRadioButton();
        sortMethodButton2 = new javax.swing.JRadioButton();
        sortMethodButton3 = new javax.swing.JRadioButton();
        randMethodButton1 = new javax.swing.JRadioButton();
        randMethodButton3 = new javax.swing.JRadioButton();
        randMethodButton2 = new javax.swing.JRadioButton();
        nThreadsLabel = new javax.swing.JLabel();
        nThreadsField = new javax.swing.JTextField();
        okButton = new javax.swing.JButton();

        setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));

        roiPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(" ROI borders "));

        regLabel.setText("Fold change");

        regField.setText("1.5");

        sigLabel.setText("Significance level");

        sigField.setText("0.05");

        javax.swing.GroupLayout roiPanelLayout = new javax.swing.GroupLayout(roiPanel);
        roiPanel.setLayout(roiPanelLayout);
        roiPanelLayout.setHorizontalGroup(
            roiPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, roiPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(roiPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, roiPanelLayout.createSequentialGroup()
                        .addComponent(sigLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(sigField, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, roiPanelLayout.createSequentialGroup()
                        .addComponent(regLabel)
                        .addGap(59, 59, 59)
                        .addComponent(regField, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        roiPanelLayout.setVerticalGroup(
            roiPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(roiPanelLayout.createSequentialGroup()
                .addGroup(roiPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(regLabel)
                    .addComponent(regField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(roiPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sigLabel)
                    .addComponent(sigField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        modelParamsPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(" Model parameters "));

        alpha1Label.setText("<html>&alpha;_1");

        alpha1Field.setText("0.75");

        alpha2Field.setText("0.15");

        alpha2Label.setText("<html>&alpha;_2");

        alpha3Field.setText("0.10");

        alpha3Label.setText("<html>&alpha;_3");

        kappa2Label.setText("<html>&kappa;_2");

        kappa2Field.setText("8.0");

        kappa1Field.setText("0.75");

        kappa1Label.setText("<html>&kappa;_1");

        javax.swing.GroupLayout modelParamsPanelLayout = new javax.swing.GroupLayout(modelParamsPanel);
        modelParamsPanel.setLayout(modelParamsPanelLayout);
        modelParamsPanelLayout.setHorizontalGroup(
            modelParamsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(modelParamsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(modelParamsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(modelParamsPanelLayout.createSequentialGroup()
                        .addComponent(alpha1Label, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(alpha1Field, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, Short.MAX_VALUE)
                        .addComponent(kappa1Label, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(kappa1Field, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(modelParamsPanelLayout.createSequentialGroup()
                        .addComponent(alpha2Label, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(alpha2Field, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, Short.MAX_VALUE)
                        .addComponent(kappa2Label, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(kappa2Field, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(modelParamsPanelLayout.createSequentialGroup()
                        .addComponent(alpha3Label, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(alpha3Field, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        modelParamsPanelLayout.setVerticalGroup(
            modelParamsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(modelParamsPanelLayout.createSequentialGroup()
                .addGroup(modelParamsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(alpha1Label, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(alpha1Field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(kappa1Label, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(kappa1Field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(modelParamsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(alpha2Label, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(alpha2Field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(kappa2Label, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(kappa2Field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(modelParamsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(alpha3Label, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(alpha3Field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        statsPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(" Statistics "));

        sortLabel.setFont(new java.awt.Font("Lucida Grande", 1, 11));
        sortLabel.setText("GSEA Sort method");

        randLabel.setFont(new java.awt.Font("Lucida Grande", 1, 11));
        randLabel.setText("Randomization");

        sortButtons.add(sortMethodButton1);
        sortMethodButton1.setSelected(true);
        sortMethodButton1.setText("[f]old change");

        sortButtons.add(sortMethodButton2);
        sortMethodButton2.setText("[p]-value");

        sortButtons.add(sortMethodButton3);
        sortMethodButton3.setText("[c]ombined");

        randButtons.add(randMethodButton1);
        randMethodButton1.setSelected(true);
        randMethodButton1.setText("[E]mpirical dist.");

        randButtons.add(randMethodButton3);
        randMethodButton3.setText("[P]ermutation");

        randButtons.add(randMethodButton2);
        randMethodButton2.setText("[L]og-normal dist");

        javax.swing.GroupLayout statsPanelLayout = new javax.swing.GroupLayout(statsPanel);
        statsPanel.setLayout(statsPanelLayout);
        statsPanelLayout.setHorizontalGroup(
            statsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(statsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(statsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(sortMethodButton1)
                    .addComponent(sortMethodButton2)
                    .addComponent(sortMethodButton3)
                    .addComponent(sortLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                .addGroup(statsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(randLabel)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, statsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(randMethodButton2)
                        .addComponent(randMethodButton1))
                    .addComponent(randMethodButton3))
                .addContainerGap())
        );
        statsPanelLayout.setVerticalGroup(
            statsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(statsPanelLayout.createSequentialGroup()
                .addGroup(statsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sortLabel)
                    .addComponent(randLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(statsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(randMethodButton1)
                    .addComponent(sortMethodButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(statsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(sortMethodButton2)
                    .addComponent(randMethodButton2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(statsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(sortMethodButton3)
                    .addComponent(randMethodButton3)))
        );

        nThreadsLabel.setText("<html># of threads");

        nThreadsField.setText("0");

        okButton.setText("OK");
        okButton.setSelected(true);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(statsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(modelParamsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(roiPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(nThreadsLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(nThreadsField, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(okButton, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(statsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(roiPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nThreadsLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nThreadsField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(okButton)))
            .addComponent(modelParamsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField alpha1Field;
    private javax.swing.JLabel alpha1Label;
    private javax.swing.JTextField alpha2Field;
    private javax.swing.JLabel alpha2Label;
    private javax.swing.JTextField alpha3Field;
    private javax.swing.JLabel alpha3Label;
    private javax.swing.JTextField kappa1Field;
    private javax.swing.JLabel kappa1Label;
    private javax.swing.JTextField kappa2Field;
    private javax.swing.JLabel kappa2Label;
    private javax.swing.JPanel modelParamsPanel;
    private javax.swing.JTextField nThreadsField;
    private javax.swing.JLabel nThreadsLabel;
    private javax.swing.JButton okButton;
    private javax.swing.ButtonGroup randButtons;
    private javax.swing.JLabel randLabel;
    private javax.swing.JRadioButton randMethodButton1;
    private javax.swing.JRadioButton randMethodButton2;
    private javax.swing.JRadioButton randMethodButton3;
    private javax.swing.JTextField regField;
    private javax.swing.JLabel regLabel;
    private javax.swing.JPanel roiPanel;
    private javax.swing.JTextField sigField;
    private javax.swing.JLabel sigLabel;
    private javax.swing.ButtonGroup sortButtons;
    private javax.swing.JLabel sortLabel;
    private javax.swing.JRadioButton sortMethodButton1;
    private javax.swing.JRadioButton sortMethodButton2;
    private javax.swing.JRadioButton sortMethodButton3;
    private javax.swing.JPanel statsPanel;
    // End of variables declaration//GEN-END:variables
    
    private final String FOLD_CH_IDENTIFIER = "[f]";
    private final String PVAL_IDENTIFIER = "[p]";
    private final String COMBINED_IDENTIFIER = "[c]";
    private final String EMPIRICAL_DIST_IDENTIFIER = "[E]";
    private final String PERMUTATION_IDENTIFIER = "[P]";
    private final String LOGNORM_IDENTIFIER = "[L]";
    
}
